### PR TITLE
Removing gulp-util; replacing with plugin-error and fancy-log

### PR DESCRIPTION
**Pull request by cjsimmons89**

### CODE REVIEW

**Comment by bestander** [comment]
Thanks for your pull request.
Is it necessary, how would it affect the experience?
Do you need to update package.json as well?

**Comment by cjsimmons89** [comment]
Gulp-util was deprecated in December 2017, so I'm just removing that dependency. 
And you're right - sorry - I didn't realize gulp-util was in the package.json. (this is my first pull request, still learning...) I am not sure if "plugin-error" and "fancy-log" should be included in package.json..? If so, I will add them. Thanks.

**Comment by cjsimmons89** [comment]
I've updated package.json: removed gutil and added the ones needed.

**Comment by bestander** [comment]
Thanks for the contribution, @cjsimmons89

**Pull request merged**
